### ISSUE TITLE
Bad_Request error message

### ISSUE THREAD

**Issue by kruny1001** [EasyPost/easypost-node#21]
I ran the example.js.
why is this error message shown?

{ message: 
   { code: 'BAD_REQUEST',
     message: 'Invalid parameters were passed and the record could not be persisted.',
     errors: [ [Object] ] },
  param: undefined }

How can I deal with this error?

**Comment by att14** [comment]
Please provide an example to reproduce the issue and reopen. Alternatively, email support@easypost.com and identify your EasyPost account by email address.

**Comment by victoryftw** [comment]
Just to follow up, example.js includes this error as an example of how to handle an error response. 

The error occurs on the `easypost.Parcel.create` line (the value being passed for the 'predefined_package' field is "InvalidPackageName"). Another parcel is defined after, showing a different way to specify a parcel object. The error is intentional and so there is no need to deal with it.
