### ISSUE TITLE
parcel - predefined_package list?

### ISSUE THREAD

**Issue by cmawhorter** [EasyPost/easypost-node#212]
is there a list of predefined_package's somewhere?  i know this kinda exists [here 
as a web page](https://www.easypost.com/service-levels-and-parcels), but does it exist somewhere in a more usable format, like json?

also -- is there anything that maps which predefined packages are available for a given service level?  for example -- with USPS -- _LargeFlatRateBox_ is never available with service level _LibraryMail_.  since i'm in the US that's an obvious one to me, but for other countries i have no idea.  

what's the recommended approach there? should i brute force it and create ~20 shipments and filter out the errors?

**Comment by Justintime50** [comment]
Thanks for writing in! There is not currently an alternative list of predefined packages per carrier/service aside from the previously linked documentation found on our website ([Service Levels](https://www.easypost.com/docs/api#service-levels), [Predefined Packages](https://www.easypost.com/docs/api#predefined-packages)).

Publishing an up-to-date list can be tricky as carriers are frequently changing which services and predefined packages are available based on availability and the rules of shipping at the time.

My best suggestion is to contact our support team who deals with these kinds of rules and availability daily. They can be contacted at support@easypost.com. As for providing a list of JSON, I think that's an excellent idea. I'll take this feature suggestion back to our team and see what we can do. If we are able to provide some kind of list, I will absolutely post an update on this ticket. As for this particular issue, I'm going too close it since it's not directly related to the Node client library. Best of luck!

**Comment by Justintime50** [comment]
@cmawhorter I was able to generate a JSON list of both our [service levels](https://github.com/Justintime50/easypost-tools/blob/7d5508c3f7a96582299bfbedbdb438eb0fbeb866/src/reference/easypost-service-levels.json) and [predefined packages](https://github.com/Justintime50/easypost-tools/blob/7d5508c3f7a96582299bfbedbdb438eb0fbeb866/src/reference/easypost-predefined-packages.json) using a [tool I wrote](https://github.com/Justintime50/easypost-tools/blob/7d5508c3f7a96582299bfbedbdb438eb0fbeb866/src/tools/python/scrape_ep_docs.py) that grabs all available data from the site and generates a JSON file from it. I hope this is helpful and gets you the data you need in the meantime of an official solution.

**Comment by cmawhorter** [comment]
thanks for putting that together. i'll take a look.

> Publishing an up-to-date list can be tricky as carriers are frequently changing which services 
> and predefined packages are available based on availability and the rules of shipping at the time

yes, definitely.  i don't have the resources to track down all this info for all the carriers easypost supports, which is why i was hoping it was exposed somehow.
