### ISSUE TITLE
[Bug]: Tracker missing delayed status_detail

### ISSUE THREAD

**Issue by dancannon** [EasyPost/easypost-node#411]
### Software Version

6.7.2

### Language Version

18.16.1

### Operating System

N/A

### What happened?

`ITrackingDetail` is missing the `description` field
`ITrackerStatusDetail` is missing the `delayed` value

### What was expected?

These values should be present in the typescript mappings

**Comment by nwithan8** [comment]
Hey @dancannon ! Thanks again for reporting this!

We're adding all the possible values for `ITrackerStatusDetail` in #412 , which will roll out with some other updates next week. Turns out there's a lot more than just "delayed" that wasn't included...

The "description" field for a `TrackingDetail` is a legacy property that can be ignored, so we won't document it. You'll notice it's almost always `null`.
