### ISSUE TITLE
[Feat]: Get Account Balance Before Purchasing Shipment

### ISSUE THREAD

**Issue by tmcallister92** [EasyPost/easypost-node#420]
### Feature Request Is New

- [X] I have verified that the requested feature does not already exist or has not already been requested.

### Description of the feature

Hey all, 

Thanks for the excellent package. Having a few issues with knowing what the balance is ahead of time. The flow is as follows. 

1. quote a shipment (succeeds with a quote)
2. attempt to purchase shipment (fails insufficent balance)

This may be outside the scope of this package, as I can't find in the API documentation that looking up the account balance is even supported. 

It would be super handy to have a method for looking up account balance, as an ability to not have to handle the error case, or proactively prompt our users to look at their EasyPost account.

Thanks

**Comment by nwithan8** [comment]
Hey @tmcallister92 , thanks for reaching out! As it stands currently, you're right, we don't have a dedicated API endpoint (and therefore no dedicated function in the library) for viewing account balances. However, the `balance` is included as part of the response when retrieving a User: https://www.easypost.com/docs/api#retrieve-a-user

You could use the [`retrieveMe`](https://easypost.github.io/easypost-node/global.html#retrieveMe) function to assess your account balance.

We've taken your comments about the endpoint under advisement, but since there's nothing to do with this library specifically, I'm going to close this ticket. Feel free to re-open it if you have any other concerns.
