### ISSUE TITLE
customs_item.value becomes string after .save

### ISSUE THREAD

**Issue by k-funk** [EasyPost/easypost-node#76]
```
new api.CustomsItem({
  description: 'T-shirt',
  quantity: 1,
  value: 10,
  weight: 5,
  hs_tariff_number: '123456',
  origin_country: 'us'
}).save(console.log);
```

`value` is now a string. This is problematic when creating a CustomsInfos:
```errors: { value: 'Error: Invalid prop `value` of type `string` supplied to `CustomsItem`, expected `number`.' }```

**Comment by Roguelazer** [comment]
`customs_info` is a Decimal and cannot safely be represented as a number in JSON

**Comment by ajacksified** [comment]
In particular, in javascript, _everything_ is a float - I'll swap this to a string, and add a note to the docs that this in particular has to be a string due to precision. I took a look and it seems that this is the only decimal property we'll be working with, at least in the current api. If/when we end up with more apis that use decimals, we can look into implementing something to work with decimals.

**Comment by k-funk** [comment]
@ajacksified it looks like there's floats/decimals on Parcels, Trackers, and CustomsItems

**Comment by ajacksified** [comment]
Floats, yeah - which return as floats, rather than strings. Decimals are only on customs_item.value, fee_tiers.amount_percent, and tracking locations lat/long.
