### ISSUE TITLE
CarrierAccount - save not implemented

### ISSUE THREAD

**Issue by mikejohanson** [EasyPost/easypost-node#82]
Hey,

Just started integrating with EasyPost, the first thing I tried to do is create a carrier account. However, I'm getting a "NotImplementedError" for the method save() on the CarrierAccount. I'm just trying to follow the docs: https://www.easypost.com/docs/api#carrier-accounts.

This blog article posted in January states that Carrier Accounts is one of the available endpoints: https://www.easypost.com/blog/2017-01-05-node-sdk-v3.html, and is also called out in: https://github.com/EasyPost/easypost-node/issues/36 as being available. 

But: https://github.com/EasyPost/easypost-node/blob/master/src/resources/carrierAccount.js#L30

I have 3.0.10 installed, what am I missing?

Thanks,

**Comment by k-funk** [comment]
I've just released `v3.0.12` which solves your issue.

However, since you're just starting out, I'm guessing that you don't need to programmatically create new CarrierAccounts, and probably just have one set of credentials per carrier. If that is the case, you can add and edit CarrierAccounts at https://www.easypost.com/account/carriers which is much easier since the `credentials` fields that are required often vary from one carrier to the next.

**Comment by mikejohanson** [comment]
Awesome! Thanks for the closing the issue! With our setup each user will be using their own carrier accounts, so we'll be making heavy use of childusers and the carrier accounts API :)
